# Generated by Django 5.2.6 on 2025-09-12 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(default='BR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima_app.cidade')),
            ],
        ),
    ]
